
networks:
  sn-project:
    name: sn-project
    external: false
    driver: bridge


services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    networks:
      - sn-project

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    ports:
      - "8089:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_ENABLED: "false"
    networks:
      - sn-project

  # backend-server:
  #   image: fsentinelle/backend-server:latest
  #   build:
  #     context: ./../../src/backend
  #     dockerfile: Dockerfile
  #   container_name: backend-server
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - sn-project
  #   volumes:
  #     - ./../../src/backend:/app
  #   ports:
  #     - "8083:8080"

  # frontend-server:
  #   image: fsentinelle/frontend-server:latest
  #   build:
  #     context: ./../../src/frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend-server
  #   depends_on:
  #     - backend-server
  #   networks:
  #     - sn-project
  #   volumes:
  #     - ./../../src/frontend:/app
  #   ports:
  #     - "3000:3000"